
package com.pers.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://service.pers/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryUser", targetNamespace = "http://service.pers/", className = "com.pers.client.QueryUser")
    @ResponseWrapper(localName = "queryUserResponse", targetNamespace = "http://service.pers/", className = "com.pers.client.QueryUserResponse")
    @Action(input = "http://service.pers/UserService/queryUserRequest", output = "http://service.pers/UserService/queryUserResponse")
    public String queryUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
