spring:
  application:
    name: HelloClient
  cloud:
    config:
      uri: http://${CONFIG_HOST:localhost}:${CONFIG_PORT:8888}
      fail-fast: true
      password: ${CONFIG_PASS:dev}
      username: user
server:
  port: ${PORT:8502}