common:
  mq:
    enable: <rabbitmq1>,<rocketmq>

# rabbit mq config
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /

# rocket mq config
rocketmq:
  name-server: localhost:9876
  producer:
      group: my-group1